### ISSUE TITLE
Possible to rearrange Pins?

### ISSUE THREAD

**Issue by bhundt** [Fattorino/ImNodeFlow#32]
Hi and first of all: thanks for the awesome project! I am currently looking for a node editor for a small project of mine. In this project I would need to connect one output pin of one node (let's call it node 1) to the input pin of another node (node 2) and than feed the outcome of the second node back into the first node. Would it be possible to move the pins around inside a node like in the attached sketch ("I": input pin, "O": output pin) to not clutter the diagram with crossing links?

<img width="452" alt="Screenshot 2024-08-02 at 12 58 02" src="https://github.com/user-attachments/assets/b273d9fb-2a33-43f5-b74e-281a30dad5f0">

**Comment by Fattorino** [comment]
I'm sorry but that would require a substantial rework of the pin and node's rendering logic. Therefore, it won't be supported any time soon, especially because of a lack of time on my part.
But if you implement this feature yourself, a PR will always be appreciated to expand the library with more features.
