### ISSUE TITLE
Feedback Connections

### ISSUE THREAD

**Issue by avlec** [Fattorino/ImNodeFlow#4]
Allow an Input Pin from a node to be able to be fed from an Output Pin of the same node. This would allow modeling of things like PID which take output signals as feedback for control modulation.

**Comment by Fattorino** [comment]
Yes, the current solution is kind of limiting. I was thinking of adding an extra flag to allow same-node connections but I'm not sure this is the best way to do it. Furthermore, I'll also have to address the problem of a looping connection causing a crash due to getting stuck in a function call loop. Both will be addressed when I'll revisit the links code but it's not one of the priorities for now.
For now, if you need such behavior the best solution is to create a dummy node whose only job is to output its input.

**Comment by Fattorino** [comment]
Added with commit 91369fc
